language: php
sudo: false
dist: trusty

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

env:
  global:
    - COMPOSER_SANDBOX_TMPDIR="$HOME/.tmp"
    - COMPOSER_SANDBOX_EXTRA_ARGS="-vv"
    - IGNORE_PLATFORM_REQS=""
  jobs:
    - COMPOSER_VERSION="1"
    - COMPOSER_VERSION="2"

php:
  - 5.6
  - 7.0
  - 7.4
  - 8.0
  - nightly

matrix:
  allow_failures:
    - php: nightly
    - php: 8.0

install: travis_retry bin/install-project

script: bin/tests-run
  
